# Generated by Django 5.0.1 on 2024-06-23 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='images')),
                ('isFeatured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='placeholder', null=True, upload_to='images')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('isFeatured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('portfolio', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='placeholder', null=True, upload_to='images')),
                ('fbLink', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Executives',
            },
        ),
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('isFeatured', models.BooleanField(default=False)),
                ('isWallpaper', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.TextField()),
                ('testifier', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
            },
        ),
    ]
