# Generated by Django 5.0.1 on 2024-06-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiomessage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='audiomessage',
            name='isFeatured',
        ),
    ]
