# Generated by Django 5.0.1 on 2024-06-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_audiomessage_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomessage',
            name='eventMessages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='event',
            name='image3',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='event',
            name='image4',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='event',
            name='subdescription',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
