# Generated by Django 5.0.1 on 2024-07-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_audiomessage_eventmessages_audiomessage_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
