# Generated by Django 5.0.1 on 2024-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_testimony_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
