# Generated by Django 5.0.1 on 2024-07-16 20:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_event_description_alter_testimony_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='executive',
            name='fbLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='testimony',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
