# Generated by Django 5.0.1 on 2024-07-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_description_alter_executive_fblink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image4',
        ),
    ]
