# Generated by Django 5.0.2 on 2024-09-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_picture_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='created_at',
        ),
    ]
