# Generated by Django 5.0.2 on 2024-09-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_picture_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomessage',
            name='by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
